### ISSUE TITLE
waitForExpect throwing error instead of waiting

### ISSUE THREAD

**Issue by robross0606** [TheBrainFamily/wait-for-expect#29]
For reasons I don't understand, attempts to use `waitForExpect()` are returning a Jest error instead of waiting (and possibly timing out).
```
    expected [] to be an array containing exactly 1 items

      429 |
      430 |           await waitForExpect(() => {
    > 431 |             expect(receivedMessages).toBeArrayOfSize(1)
          |                                      ^
      432 |           })
      433 |

      at src/__tests__/amqp-service.test.js:431:38
      at Timeout.runExpectation [as _onTimeout] (node_modules/wait-for-expect/lib/index.js:46:25)
```

**Comment by robross0606** [comment]
Or is the problem that it _is_ timing out? If so, it is doing so very quickly.

**Comment by robross0606** [comment]
I should note that this didn't start happening until I had two different `waitForExpect()` calls at two different spots in the same unit test.  Could the timer not be resetting between those calls?

**Comment by lgandecki** [comment]
Hey there, sorry for the troubles - any chance you could push a tiny reproduction to github?

**Comment by robross0606** [comment]
yes, I'm trying to reproduce in a smaller test right now

**Comment by robross0606** [comment]
I was able to reproduce this very easily with the following code:
```javascript
const waitForExpect = require('wait-for-expect')

function sleep(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms)
  })
}

const received = []
async function doSomethingLong() {
  await sleep(5000)
  received.push(received.length + 1)
}

test('Testing wait-for-expect', async () => {
  doSomethingLong()

  await waitForExpect(() => {
    expect(received.length).toBe(1)
  })

  doSomethingLong()

  await waitForExpect(() => {
    expect(received.length).toBe(5)
  })
})
```
Produces:
```
  ● Testing wait-for-expect

    expect(received).toBe(expected) // Object.is equality

    Expected: 5
    Received: 2

      23 |
      24 |   await waitForExpect(() => {
    > 25 |     expect(received.length).toBe(5)
         |                             ^
      26 |   })
      27 | })
      28 |

      at src/__tests__/waitForExpect.test.js:25:29
      at Timeout.runExpectation [as _onTimeout] (node_modules/wait-for-expect/lib/index.js:46:25)
```

**Comment by robross0606** [comment]
I was able to reproduce this very easily with the following code:
```javascript
const waitForExpect = require('wait-for-expect')

function sleep(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms)
  })
}

const received = []
async function doSomethingLong() {
  await sleep(5000)
  received.push(received.length + 1)
}

test('Testing wait-for-expect', async () => {
  doSomethingLong()

  await waitForExpect(() => {
    expect(received.length).toBe(1)
  })

  doSomethingLong()

  await waitForExpect(() => {
    expect(received.length).toBe(5)
  })
})
```
Produces:
```
  ● Testing wait-for-expect

    expect(received).toBe(expected) // Object.is equality

    Expected: 5
    Received: 2

      23 |
      24 |   await waitForExpect(() => {
    > 25 |     expect(received.length).toBe(5)
         |                             ^
      26 |   })
      27 | })
      28 |

      at src/__tests__/waitForExpect.test.js:25:29
      at Timeout.runExpectation [as _onTimeout] (node_modules/wait-for-expect/lib/index.js:46:25)
```
I'm not sure if this is expected or not since the stack trace location of the failure is different than what is shown on your README.md:
```
      at waitForExpect (src/waitForExpect.spec.js:13:34)
      at waitUntil.catch (src/index.js:61:5)
```

**Comment by robross0606** [comment]
I think it just may be that the README documentation is slightly outdated and this is a normal indication that `waitForExpect()` waited and never found the expected result.
